---
- hosts: all
  vars_files:
    - vars/spark.yaml
  become: yes
  tasks:

    - name: Kill java
      shell:
        cmd: pkill -9 java
      ignore_errors: yes

    - name: Remove packages Centos
      yum:
        name: "{{ packages }}"
        state: absent
        update_cache: no
      vars:
        packages:
        - atop
        - htop
        - netdata
        - irqbalance
        - java-8-openjdk
        - scala
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
      tags: packages
      ignore_errors: yes

    - name: Remove packages Ubuntu
      apt:
        name: "{{ packages }}"
        state: absent
        update_cache: no
      vars:
        packages:
        - atop
        - htop
        - netdata
        - tuned
        - irqbalance
        - openjdk-8-jre-headless
        - scala
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      tags: packages
      ignore_errors: yes

    - name: Removing the path from /etc/environment
      lineinfile:
        dest: /etc/environment
        regexp: 'SPARK'
        state: absent
      become: yes
      tags: spark
      ignore_errors: yes

- hosts: master
  vars_files:
    - vars/spark.yaml
  become: yes
  tasks:
 
    - name: Delete spark directory
      file:
        path: '{{ CONFIG }}/spark'
        state: absent
      tags: spark
      ignore_errors: yes

    - name: Delete sparkRapidsPlugin directory
      file:
        path: '{{ CONFIG }}/sparkRapidsPlugin'
        state: absent
      tags: spark
      ignore_errors: yes
      
