---
- hosts: all
  become: yes
  tasks:

    - apt_repository:
        repo: 'ppa:graphics-drivers'

    - name: add cuda repo keys
      shell:
        cmd: apt-key adv --fetch-keys  http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
      tags: config
 
    - name: add cuda repo
      shell:
        cmd: bash -c 'echo "deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64 /" > /etc/apt/sources.list.d/cuda.list'
      tags: config

    - name: add cuda_learn repo
      shell:
        cmd: bash -c 'echo "deb http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64 /" > /etc/apt/sources.list.d/cuda_learn.list'
      tags: config

    - name: Install packages Ubuntu
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - cuda-10-1
        - libcudnn7
        - nvidia-cuda-toolkit
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      tags: packages

    - name: 'Add {{ extra_path }} to PATH'
      lineinfile:
        path: /etc/environment
        regexp: 'PATH=(["])((?!.*?/usr/local/cuda-10.1/bin${PATH:+:${PATH}}).*?)(["])$'
        line: 'PATH=\1\2:/usr/local/cuda-10.1/bin${PATH:+:${PATH}}\3'
        backrefs: yes
      when: lookup('file', '/etc/environment') is search('^\s*PATH\s*=')
      tags: test1
    
    
    - name: Adding LD_LIBRARY to /etc/environment
      lineinfile:
        dest: /etc/environment
        line: 'LD_LIBRARY_PATH="/usr/local/cuda-10.1/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"'
        insertafter: 'EOF'
        regexp: 'LD_LIBRARY_PATH="/usr/local/cuda-10.1/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"'
        state: present
      become: yes
      tags: config
  
    - name: show cuda version
      environment:
        PATH: "/usr/local/cuda-10.1/bin${PATH:+:${PATH}}"
        LD_LIBRARY_PATH: "/usr/local/cuda-10.1/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"
      shell:
        cmd: nvcc --version 
      tags: config

    - name: show nvidia-smi tool
      environment:
        PATH: "/usr/local/cuda-10.1/bin${PATH:+:${PATH}}"
        LD_LIBRARY_PATH: "/usr/local/cuda-10.1/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"
      shell:
        cmd: nvidia-smi
      tags: config
